package shop.haui_megatech.domain.entity.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
@Getter
public enum Authority {
    READ_PRODUCT("READ_PRODUCT"),
    READ_ACTIVE_PRODUCTS("READ_ACTIVE_PRODUCTS"),
    READ_HIDDEN_PRODUCTS("READ_HIDDEN_PRODUCTS"),
    READ_DELETED_PRODUCTS("READ_DELETED_PRODUCTS"),
    CREATE_PRODUCT("CREATE_PRODUCT"),
    UPDATE_PRODUCT("UPDATE_PRODUCT"),
    SOFT_DELETE_PRODUCT("SOFT_DELETE_PRODUCT"),
    RESTORE_PRODUCT("RESTORE_PRODUCT"),
    HARD_DELETE_PRODUCT("HARD_DELETE_PRODUCT"),
    HIDE_PRODUCT("HIDE_PRODUCT"),
    EXPOSE_PRODUCT("EXPOSE_PRODUCT"),
    IMPORT_EXCEL_PRODUCT("IMPORT_EXCEL_PRODUCT"),
    IMPORT_CSV_PRODUCT("IMPORT_CSV_PRODUCT"),

    READ_USER("READ_USER"),
    READ_ACTIVE_USERS("READ_ACTIVE_USERS"),
    READ_DELETED_USERS("READ_DELETED_USERS"),
    CREATE_USER("CREATE_USER"),
    UPDATE_INFO("UPDATE_INFO"),
    UPDATE_OTHERS("UPDATE_OTHERS"),
    SOFT_DELETE_USER("SOFT_DELETE_USER"),
    RESTORE_USER("RESTORE_USER"),
    HARD_DELETE_USER("HARD_DELETE_USER"),
    RESET_PASSWORD("RESET_PASSWORD"),
    UPDATE_PASSWORD("UPDATE_PASSWORD"),
    IMPORT_EXCEL_USER("IMPORT_EXCEL_USER"),
    IMPORT_CSV_USER("IMPORT_CSV_USER"),

    READ_FEEDBACK("READ_FEEDBACK"),
    CREATE_FEEDBACK("CREATE_FEEDBACK"),
    UPDATE_FEEDBACK("UPDATE_FEEDBACK"),

    CREATE_PAYMENT("CREATE_PAYMENT"),

    READ_ORDER("READ_ORDER"),
    CREATE_ORDER("CREATE_ORDER"),
    UPDATE_ORDER("UPDATE_ORDER"),
    DELETE_ORDER("DELETE_ORDER"),

    CREATE_ADDRESS("CREATE_ADDRESS"),
    UPDATE_ADDRESS("UPDATE_ADDRESS"),
    DELETE_ADDRESS("DELETE_ADDRESS"),

    READ_BRAND("READ_BRAND"),

    READ_CART_ITEM("READ_CART_ITEM"),
    CREATE_CART_ITEM("CREATE_CART_ITEM"),
    UPDATE_CART_ITEM("UPDATE_CART_ITEM"),
    DELETE_CART_ITEM("DELETE_CART_ITEM"),


    ;

    private final String name;
}
