package shop.haui_megatech.domain.entity.enums;

public enum Authority {
    READ_PRODUCT,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    SOFT_DELETE_PRODUCT,
    RESTORE_PRODUCT,
    HARD_DELETE_PRODUCT,
    HIDE_PRODUCT,
    EXPOSE_PRODUCT,
    IMPORT_EXCEL_PRODUCT,
    IMPORT_CSV_PRODUCT,

    READ_USER,
    CREATE_USER,
    UPDATE_USER,
    SOFT_DELETE_USER,
    RESTORE_USER,
    HARD_DELETE_USER,
    RESET_PASSWORD_USER,
    IMPORT_EXCEL_USER,
    IMPORT_CSV_USER,

    READ_BRAND,
    CREATE_BRAND,
    UPDATE_BRAND,
    SOFT_DELETE_BRAND,
    RESTORE_BRAND,
    HARD_DELETE_BRAND,
}
